export enum DealLineEnum {
  Admiral = 'Admiral',
  ARKAS = 'ARKAS',
  CMA = 'CMA',
  COSCO = 'COSCO',
  COSCO_SUPRA = 'COSCO-Supra',
  EMC = 'EMC',
  HPL = 'HPL',
  MAE = 'MAE',
  MSC = 'MSC',
  NDL = 'NDL',
  ONE = 'ONE',
  OOCL = 'OOCL',
  Sealand = 'Sealand',
  Turkon = 'Turkon',
  UASC = 'UASC',
  YML = 'YML',
  ZIM = 'ZIM',
}
